[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.scripts]
your_script_name = {executable = "main_script:game.py"}

